"""add note timestamp

Revision ID: 41057de5ccd9
Revises: 
Create Date: 2022-03-11 12:07:40.449648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41057de5ccd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'timestamp')
    # ### end Alembic commands ###
